setopt AUTO_CD INTERACTIVE_COMMENTS
setopt NO_BEEP
setopt EXTENDED_GLOB

HISTFILE="$ZSH_CACHE_DIR/history"
HISTSIZE=100000
SAVEHIST=100000
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_VERIFY
setopt SHARE_HISTORY INC_APPEND_HISTORY
